from fastapi import FastAPI, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from fastapi.exceptions import RequestValidationError
from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.responses import JSONResponse

from app.core.config import settings
from app.core.middleware import SolisRateLimitMiddleware, SecurityHeadersMiddleware
from app.core.exceptions import SolisError
from app.core.logging import logger
from app.api.endpoints import diagnostics, inverters, collectors, epms, weather, stations

app = FastAPI(
    title="SolisCloud Platform API Mock System",
    description="""
    ### ⚡ Commercial-Grade SolisCloud API Mock System (V2.0)
    
    Welcome to the secure, high-performance modular simulation of the **Ginlong (Solis) Technologies SolisCloud Platform API V2.0**.
    
    This API replicates the telemetry data collection, power station lookups, inverter stats, alarm metrics, and meteorological outputs generated by Solis inverters.
    
    #### 🔒 Key Enterprise Enhancements:
    * **Constant-Time HMAC Authentication**: Mitigates timing attacks by validating all `Authorization` signatures via `hmac.compare_digest` with absolute Content-MD5 verification.
    * **Active Replay & Skew Defense**: Automatically blocks stale requests exceeding a 15-minute date skew window.
    * **Multi-Tenant Access Safeguards (IDOR Defense)**: Ensures that API Clients can only query stations and devices belonging specifically to their own tenant record.
    * **In-Memory Token-Bucket Rate Limiting**: Separately limits inverter endpoints (`RATE_LIMIT_INVERTER`) and general resource paths (`RATE_LIMIT_OTHER`) to mitigate DDoS risks.
    * **Masked Structural Logs**: Masks API keys, signatures, and secrets before dumping telemetry into standard console channels.
    """,
    version="2.0.0",
    contact={
        "name": "Enterprise Engineering Team",
        "email": "engineering@enterprise-solutions.com",
    },
    license_info={
        "name": "MIT License",
        "url": "https://opensource.org/licenses/MIT",
    }
)

# --- Global Exception Handlers for Unified API Contract ---

@app.exception_handler(SolisError)
async def solis_exception_handler(request: Request, exc: SolisError):
    # Log business errors beautifully
    if exc.http_status_code == status.HTTP_403_FORBIDDEN:
        logger.warning(f"[SECURITY ALERT] Tenancy (IDOR) violation on {request.url.path}: {exc.msg}")
    elif exc.http_status_code == status.HTTP_429_TOO_MANY_REQUESTS:
        logger.warning(f"[RATE LIMIT] Limit reached on {request.url.path}: {exc.msg}")
    else:
        logger.warning(f"Business Error: Code={exc.code}, Msg={exc.msg}, Path={request.url.path}")
        
    return JSONResponse(
        status_code=exc.http_status_code,
        content={
            "success": False,
            "code": exc.code,
            "msg": exc.msg,
            "data": None
        }
    )

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    errors = exc.errors()
    detail_msg = "; ".join([f"{err['loc'][-1]}: {err['msg']}" for err in errors])
    logger.warning(f"Validation Error: Msg={detail_msg}, Path={request.url.path}")
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={
            "success": False,
            "code": "422",
            "msg": f"Parameters validation error: {detail_msg}",
            "data": None
        }
    )

@app.exception_handler(StarletteHTTPException)
async def starlette_http_exception_handler(request: Request, exc: StarletteHTTPException):
    logger.warning(f"HTTP Exception: Code={exc.status_code}, Msg={exc.detail}, Path={request.url.path}")
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "success": False,
            "code": str(exc.status_code),
            "msg": exc.detail,
            "data": None
        }
    )

# --- Standard secure middlewares ---
app.add_middleware(TrustedHostMiddleware, allowed_hosts=settings.ALLOWED_HOSTS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["POST", "GET", "OPTIONS"],
    allow_headers=["*"],
)
app.add_middleware(GZipMiddleware, minimum_size=1000)

# --- Custom secure middlewares ---
app.add_middleware(SolisRateLimitMiddleware)
app.add_middleware(SecurityHeadersMiddleware)

# --- Include sub-routers ---
app.include_router(diagnostics.router)
app.include_router(inverters.router, prefix="/v1/api")
app.include_router(collectors.router, prefix="/v1/api")
app.include_router(epms.router, prefix="/v1/api")
app.include_router(weather.router, prefix="/v1/api")
app.include_router(stations.router, prefix="/v1/api")
